[theme]
primaryColor = "#2E86C1"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#EAECEE"
textColor = "#2C3E50"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
headless = true
runOnSave = true
port = 8501
maxUploadSize = 200